# Generated by Django 5.1.7 on 2025-03-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('ultra-rare', 'Ultra-Rare'), ('legendary', 'Legendary')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('age', models.CharField(choices=[('newborn', 'Newborn'), ('reborn', 'Reborn'), ('full', 'Full Grown')], max_length=50)),
                ('props', models.CharField(blank=True, max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('img', models.URLField(blank=True)),
            ],
        ),
    ]
